
package atj.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AttachService", targetNamespace = "http://ws.atj/", wsdlLocation = "http://localhost:8080/SOAPAttach/AttachService?wsdl")
public class AttachService
    extends Service
{

    private final static URL ATTACHSERVICE_WSDL_LOCATION;
    private final static WebServiceException ATTACHSERVICE_EXCEPTION;
    private final static QName ATTACHSERVICE_QNAME = new QName("http://ws.atj/", "AttachService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/SOAPAttach/AttachService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ATTACHSERVICE_WSDL_LOCATION = url;
        ATTACHSERVICE_EXCEPTION = e;
    }

    public AttachService() {
        super(__getWsdlLocation(), ATTACHSERVICE_QNAME);
    }

    public AttachService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ATTACHSERVICE_QNAME, features);
    }

    public AttachService(URL wsdlLocation) {
        super(wsdlLocation, ATTACHSERVICE_QNAME);
    }

    public AttachService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ATTACHSERVICE_QNAME, features);
    }

    public AttachService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AttachService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Attach
     */
    @WebEndpoint(name = "AttachPort")
    public Attach getAttachPort() {
        return super.getPort(new QName("http://ws.atj/", "AttachPort"), Attach.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Attach
     */
    @WebEndpoint(name = "AttachPort")
    public Attach getAttachPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.atj/", "AttachPort"), Attach.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ATTACHSERVICE_EXCEPTION!= null) {
            throw ATTACHSERVICE_EXCEPTION;
        }
        return ATTACHSERVICE_WSDL_LOCATION;
    }

}
