
package atj.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Attach", targetNamespace = "http://ws.atj/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Attach {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "uploadFile", targetNamespace = "http://ws.atj/", className = "atj.ws.UploadFile")
    @ResponseWrapper(localName = "uploadFileResponse", targetNamespace = "http://ws.atj/", className = "atj.ws.UploadFileResponse")
    @Action(input = "http://ws.atj/Attach/uploadFileRequest", output = "http://ws.atj/Attach/uploadFileResponse")
    public boolean uploadFile(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        byte[] arg1);

}
