
package atj.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Calc", targetNamespace = "http://ws.atj/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Calc {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sub", targetNamespace = "http://ws.atj/", className = "atj.ws.Sub")
    @ResponseWrapper(localName = "subResponse", targetNamespace = "http://ws.atj/", className = "atj.ws.SubResponse")
    @Action(input = "http://ws.atj/Calc/subRequest", output = "http://ws.atj/Calc/subResponse")
    public float sub(
        @WebParam(name = "arg0", targetNamespace = "")
        float arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        float arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "mul", targetNamespace = "http://ws.atj/", className = "atj.ws.Mul")
    @ResponseWrapper(localName = "mulResponse", targetNamespace = "http://ws.atj/", className = "atj.ws.MulResponse")
    @Action(input = "http://ws.atj/Calc/mulRequest", output = "http://ws.atj/Calc/mulResponse")
    public float mul(
        @WebParam(name = "arg0", targetNamespace = "")
        float arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        float arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "div", targetNamespace = "http://ws.atj/", className = "atj.ws.Div")
    @ResponseWrapper(localName = "divResponse", targetNamespace = "http://ws.atj/", className = "atj.ws.DivResponse")
    @Action(input = "http://ws.atj/Calc/divRequest", output = "http://ws.atj/Calc/divResponse")
    public float div(
        @WebParam(name = "arg0", targetNamespace = "")
        float arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        float arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://ws.atj/", className = "atj.ws.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://ws.atj/", className = "atj.ws.AddResponse")
    @Action(input = "http://ws.atj/Calc/addRequest", output = "http://ws.atj/Calc/addResponse")
    public float add(
        @WebParam(name = "arg0", targetNamespace = "")
        float arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        float arg1);

}
